name: CI

on:
  merge_group:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: true
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install --yes libx11-dev
      - uses: golangci/golangci-lint-action@v9
        with:
          version: v2.12.0
          only-new-issues: true

  test-linux:
    name: Test (Linux)
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: true
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install --yes libx11-dev
      - name: Run tests
        run: go test -v ./...

  test-macos:
    name: Test (macOS)
    runs-on: macos-26
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: true
      - name: Run tests
        run: go test -v ./...
